# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 847885e13ad4fb8be73033835aa8dda0df65dc10d60f3ac0492309bf74c852e28cb5159b23e414a702e88b4d4cf17a658abc9ffafbd80dc37515e028c3d97fed

test:
  secret_key_base: 5300aa470b91d7cb5709967fba1c843b34e9db86d72b716f96c310600690998863bcf97f52bca5ff411fb05063493640a88931a3af0572f10bf4effad4564c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
